import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Metadata } from "next";
import WalletProvider from "../providers/Walletprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <WalletProvider>
          <Navbar />
          <div className={`mt-[100px]`}>{children}</div>
        </WalletProvider>
      </body>
    </html>
  );
}
