import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Metadata } from "next";
import WalletProvider from "../providers/Walletprovider";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative bg-[url("https://assets-global.website-files.com/6433c5d029c6bb75f3f00bd5/64479243051b3339c7b8a81c_Group%201000002141.svg")] bg-center`}
      >
        <WalletProvider>
          <Navbar />
          <div className={`mt-[100px]`}>{children}</div>
        </WalletProvider>
      </body>
    </html>
  );
}
